### ISSUE TITLE
/co rollback only partly works

### ISSUE THREAD

**Issue by lstone01** [Drustcraft/Drustcraft-Game#14]
When you use /co rollback you have to keep repeating it as the command doesn't fill in the entire area.

**Comment by nomadjimbob** [comment]
I’m guessing this was used in an attempt to rollback Worldedit changes made? Coreprotect does not officially work with FAWE changes and there is no plan to fix it as FAWE has its own undo tools

**Comment by lstone01** [comment]
nope, it was with tnt

**Comment by nomadjimbob** [comment]
You manually placed tnt? Any other details to try and replicate this? I’ll need to try this myself and video it so it can be sent to the coreprotect team for investigation

**Comment by lstone01** [comment]
i'll try without tnt later

**Comment by lstone01** [comment]
It seems to be working now
