### ISSUE TITLE
Expand and complete the train network

### ISSUE THREAD

**Issue by nomadjimbob** [Drustcraft/Drustcraft-Game#2]
The train system currently runs from Lucas Outpost to Ironport through to the village. The following is needed to complete the tracks:

- [ ] Continue track to Scarlettville
- [ ] Build station at Scarlettville
- [ ] Finish the train track features (lighting, bridge supports)
- [ ] World protect the tracks (minimally) using region names region_XXX and a region type of railway
- [ ] Name the village and place it in its own region with a title!
- [ ] Fix the train spawn/destroy location

Do we need additional smaller stations along the current track?

Do the larger stations need to become interchanges instead. Trains are spawned/destroyed at the station?
Downsides:
- This would force players to change trains at each major station
- Stations would need to be larger to accommodate more tracks
Upside:
- Any train issues would be limited to only a smaller section of track and not the entire network

**Comment by lstone01** [comment]
Trains are no longer used.

**Comment by lstone01** [comment]
Closing
